version: 2
updates:
  # Enable version updates for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Lima"
    open-pull-requests-limit: 10
    reviewers:
      - "perujug"
    assignees:
      - "perujug"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "maven"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "io.quarkus.platform:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "io.quarkiverse.roq:*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Lima"
    open-pull-requests-limit: 5
    reviewers:
      - "perujug"
    assignees:
      - "perujug"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker dependencies (if any)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Lima"
    open-pull-requests-limit: 5
    reviewers:
      - "perujug"
    assignees:
      - "perujug"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for npm dependencies (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Lima"
    open-pull-requests-limit: 5
    reviewers:
      - "perujug"
    assignees:
      - "perujug"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "npm" 